apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-credentials-secret
spec:
  data:
    - secretKey: id_rsa
      remoteRef:
        key: d0eb6d2e-3495-434d-fb76-be7efb5c0200
    - secretKey: known_hosts
      remoteRef:
        key: ed83cc61-b789-fcde-4785-dc9ef96f198a
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: otp-repo-ssh-bot-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa: "{{ .id_rsa | toString }}"
        known_hosts: "{{ .known_hosts | toString }}"
        config: ""
