---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cluster-claimer-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: cluster-claimer-trigger-binding
      template:
        ref: cluster-claimer-service-trigger-template